server:
  port: 19091

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/user/**, /api/v1/admin/user/**, /api/v1/company/**, /api/v1/admin/company/**
        - id: slack-service
          uri: lb://slack-service
          predicates:
            - Path=/api/v1/slack/**, /api/v1/admin/slack/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/v1/ai/**
        - id: hub-service
          uri: lb://hub-service
          predicates:
            - Path=/api/v1/hubs/**, /api/v1/admin/hubs/**
        - id: delivery-driver-service
          uri: lb://delivery-driver-service
          predicates:
            - Path=/api/v1/delivery-driver/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/order/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/delivery/**

      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/